{"uuid": "718b0289-b0f0-41b3-924a-91a04b5e6ab3", "children": ["1ec3e322-3d63-48a4-a892-377230d598bf"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.264)\nStacktrace:\n#0 0x55a23a4a91fa <unknown>\n#1 0x55a239fb9810 <unknown>\n#2 0x55a239f8f48f <unknown>\n#3 0x55a23a0349bd <unknown>\n#4 0x55a23a04a9bc <unknown>\n#5 0x55a23a02c323 <unknown>\n#6 0x55a239ffade0 <unknown>\n#7 0x55a239ffbdbe <unknown>\n#8 0x55a23a47512b <unknown>\n#9 0x55a23a4790c7 <unknown>\n#10 0x55a23a4626cc <unknown>\n#11 0x55a23a479c47 <unknown>\n#12 0x55a23a44767f <unknown>\n#13 0x55a23a498288 <unknown>\n#14 0x55a23a498450 <unknown>\n#15 0x55a23a4a8076 <unknown>\n#16 0x7f8e6004c609 start_thread\n\n", "trace": "  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/vvdn/Downloads/Test_Automation/Testcases/conftest.py\", line 38, in get_browser\n    driver.maximize_window()\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 536, in maximize_window\n    self.execute(command, None)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739786956997, "stop": 1739786959733}], "start": 1739786956997, "stop": 1739786959896}