{"uuid": "6e29660d-9371-491f-8423-65e6a369ea90", "children": ["41546a4f-5479-4568-ba58-fac316d5583e"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.264)\nStacktrace:\n#0 0x55a1ee3ba1fa <unknown>\n#1 0x55a1edeca810 <unknown>\n#2 0x55a1edea048f <unknown>\n#3 0x55a1edf459bd <unknown>\n#4 0x55a1edf5b9bc <unknown>\n#5 0x55a1edf3d323 <unknown>\n#6 0x55a1edf0bde0 <unknown>\n#7 0x55a1edf0cdbe <unknown>\n#8 0x55a1ee38612b <unknown>\n#9 0x55a1ee38a0c7 <unknown>\n#10 0x55a1ee3736cc <unknown>\n#11 0x55a1ee38ac47 <unknown>\n#12 0x55a1ee35867f <unknown>\n#13 0x55a1ee3a9288 <unknown>\n#14 0x55a1ee3a9450 <unknown>\n#15 0x55a1ee3b9076 <unknown>\n#16 0x7f5107f5d609 start_thread\n\n", "trace": "  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/vvdn/Downloads/Test_Automation/Testcases/conftest.py\", line 38, in get_browser\n    driver.maximize_window()\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 536, in maximize_window\n    self.execute(command, None)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739786959901, "stop": 1739786964233}], "start": 1739786959901, "stop": 1739786964302}