{"uuid": "aec4f4fd-2fa6-43ee-9410-117c1720edb3", "children": ["0a6f2170-7667-4e4a-b3cd-9e7a368cd4b5"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.264)\nStacktrace:\n#0 0x55a54c4cb1fa <unknown>\n#1 0x55a54bfdb810 <unknown>\n#2 0x55a54bfb148f <unknown>\n#3 0x55a54c0569bd <unknown>\n#4 0x55a54c06c9bc <unknown>\n#5 0x55a54c04e323 <unknown>\n#6 0x55a54c01cde0 <unknown>\n#7 0x55a54c01ddbe <unknown>\n#8 0x55a54c49712b <unknown>\n#9 0x55a54c49b0c7 <unknown>\n#10 0x55a54c4846cc <unknown>\n#11 0x55a54c49bc47 <unknown>\n#12 0x55a54c46967f <unknown>\n#13 0x55a54c4ba288 <unknown>\n#14 0x55a54c4ba450 <unknown>\n#15 0x55a54c4ca076 <unknown>\n#16 0x7fe332842609 start_thread\n\n", "trace": "  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/vvdn/Downloads/Test_Automation/Testcases/conftest.py\", line 38, in get_browser\n    driver.maximize_window()\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 536, in maximize_window\n    self.execute(command, None)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/vvdn/Downloads/Test_Automation/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739787750696, "stop": 1739787756234}], "start": 1739787750696, "stop": 1739787756354}